### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by OlegVN** [hyphop/orange-pi-zero-kernel#1]
Hi!
Sorry for my bad English.
I need to connect a USB-Lan adapter asix ax88179
to OrangePi Zero (3.4.113-sun8i OpenWrt). But unfortunately I couldn't make the driver by manual - https://github.com/FreddyXin/ax88179_178a. Could you help me with this? I will be most grateful if you
make this driver for 3.4.113-sun8i kernel or tell me how to do it.
Best regards,
Oleg

**Comment by hyphop** [comment]
ok u can use russian )))
Где ядро брал ?
у моего ядра этот модуль есть
/tmp/zero_builder/miZy-linux-kernel/kernel-configs# grep
CONFIG_USB_NET_AX8817X default
CONFIG_USB_NET_AX8817X=m


https://github.com/hyphop/miZy-linux-kernel



2017-08-26 23:15 GMT+07:00 OlegVN <notifications@github.com>:

**Comment by hyphop** [comment]
на всяк случай
https://github.com/hyphop/miZy-linux-kernel/releases/download/default/miZy.linux.kernel.default.modules.full.tar.gz

2017-08-28 23:49 GMT+07:00 Artem AiRadio <ai.radio.org@gmail.com>:

**Comment by OlegVN** [comment]
Добрый день!
Большое спасибо за ответ!
ставил вот этот образ: 
http://www.orangepi.org/downloadresources/orangepizero/2017-05-05/orangepizero_f76137cbe2e0f38f8d5b32c.html
Фото работающего Openwrt:
![image](https://user-images.githubusercontent.com/31215699/29840534-05c0601c-8d0b-11e7-8775-21d1933e7029.png)

**Comment by hyphop** [comment]
так это не мое ядро ) причем здесь я ?  бери мое там есть все что нужно и
даже больше

2017-08-30 2:41 GMT+07:00 OlegVN <notifications@github.com>:

**Comment by OlegVN** [comment]
Понял, спасибо за пояснение, версии ядра просто одинаковые... 
Я бы с радостью взял это ядро, но не совсем понимаю как на него портировать OpenWRT, точнее пакеты от OpeenWrt.
Может быть есть возможность взять (собрать) из вашего ядра модуль (драйвер) для ax88179 или это не возможно?
Я так понимаю, ядро на моём устройстве - это ваше ядро, только урезанное?

**Comment by hyphop** [comment]
вариантов много !
1) попробуй подгрузить собранный модуль от сюда - повезет загрузится - не повезет пробуй дальше
2) просто взять ядро и модули тут - и использовать в твоей сборке Openwrt - сам он к ядру не сильно привязан но тут надо осторожно с пакетами и их зависемостями (можешь посмотреть к примеру сборку mizy - основа там тотже openwrt )
3) бери openwrt sdk - и собирай ядро и модули как тебу нужно
4) бери готовую сборку mizy - основа тотже openwrt  - есть кое где своя специфика + все еще в стадии тестирования но использовать уже можно

**Comment by OlegVN** [comment]
Спасибо за ответ!
Если первый способ, то где взять этот модуль? Я не нашёл здесь этого модуля, может он как-то по-другому называется..?

**Comment by hyphop** [comment]
Привет
я же писал где его брать)
wget https://github.com/hyphop/miZy-linux-kernel/releases/download/default/miZy.linux.kernel.default.modules.all.tar.gz
tar -xf miZy.linux.kernel.default.modules.all.tar.gz modules.all/asix.ko
разве это не он???

**Comment by hyphop** [comment]
AX8817X=m - хотя не факт что он есть)

**Comment by OlegVN** [comment]
Да, в моей прошивке тоже есть asix.ko, но адаптер не завёлся. Исходя из инструкции -https://github.com/FreddyXin/ax88179_178a, я так понял, что нужен ax88179.ko для версии ядра 3.4.113-sun8i...

**Comment by OlegVN** [comment]
Вероятнее всего модуля asix.ko не достаточно, в инструкции расписано как собрать модуль драйвера, но у меня ничего не вышло (возможно из-за недостатка опыта)

**Comment by hyphop** [comment]
ok уже вижу другой ))) модуль ax88179_178a.ko собрался из исходников http://www.asix.com.tw/products.php?op=pItemdetail&PItemID=131;71;112
в ближ время выложу

**Comment by OlegVN** [comment]
Спасибо! Жду с нетерпением!

**Comment by hyphop** [comment]
готово! тестируй!!!
[root@localhost template]# modprobe usbnet
[root@localhost template]# insmod ax88179_178a.ko
If you want to unload the driver, just executing the following command:
[root@localhost anywhere]# rmmod axax88179_178a
отпишись какие результаты - так как у меня такого девайса нет

**Comment by hyphop** [comment]
дальнейшие сообщения оставляй там так как изменения там а не тут - тут закрываю эту ветку
https://github.com/hyphop/miZy-linux-kernel
